version: "3.8"

services:
  spark-master:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../app:/app
      - ../data:/data
    networks:
      - net

  spark-worker:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:  
      - ../app:/app
      - ../data:/data
    networks:
      - net

  # spark-history-server:
  #   image: bitnami/spark:3.5.1
  #   entrypoint:  ['start-history-server.sh']
  #   ports:
  #     - "18080:18080"
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - net

  spark-connect:
    image: bitnami/spark:3.5.1
    # command:
    #   - "/bin/bash"
    #   - "-c"
    #   - ""
    command: sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.5.1
    volumes:
      - ../app:/app
      - ../data:/data
    ports:
      - "15002:15002"
    depends_on:
      - spark-master
    networks:
      - net

  
  # docker-proxy:
  #   image: bobrik/socat
  #   command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
  #   ports:
  #     - "2376:2375"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - airflow-kafka

networks:
  net:
    driver: bridge


